import Toybox.Lang;

// GENERATED by garmin/shared/tools/hko_stations.py - edit that script, not this file.
//
//! The station picker's rows: ids in menu order (Off first, then A-Z by name) and the
//! matching name resources (garmin/shared/resources-hko).
module HkoNames {

    const IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39] as Array<Number>;

    function names() as Array<ResourceId> {
        return [Rez.Strings.hkoSt0, Rez.Strings.hkoSt1, Rez.Strings.hkoSt2, Rez.Strings.hkoSt3, Rez.Strings.hkoSt4, Rez.Strings.hkoSt5, Rez.Strings.hkoSt6, Rez.Strings.hkoSt7, Rez.Strings.hkoSt8, Rez.Strings.hkoSt9, Rez.Strings.hkoSt10, Rez.Strings.hkoSt11, Rez.Strings.hkoSt12, Rez.Strings.hkoSt13, Rez.Strings.hkoSt14, Rez.Strings.hkoSt15, Rez.Strings.hkoSt16, Rez.Strings.hkoSt17, Rez.Strings.hkoSt18, Rez.Strings.hkoSt19, Rez.Strings.hkoSt20, Rez.Strings.hkoSt21, Rez.Strings.hkoSt22, Rez.Strings.hkoSt23, Rez.Strings.hkoSt24, Rez.Strings.hkoSt25, Rez.Strings.hkoSt26, Rez.Strings.hkoSt27, Rez.Strings.hkoSt28, Rez.Strings.hkoSt29, Rez.Strings.hkoSt30, Rez.Strings.hkoSt31, Rez.Strings.hkoSt32, Rez.Strings.hkoSt33, Rez.Strings.hkoSt34, Rez.Strings.hkoSt35, Rez.Strings.hkoSt36, Rez.Strings.hkoSt37, Rez.Strings.hkoSt38, Rez.Strings.hkoSt39] as Array<ResourceId>;
    }
}
