import Toybox.Application;
import Toybox.Lang;

// GENERATED by garmin/shared/tools/hko_stations.py - edit that script, not this file.
//
//! The HKO station table, indexed by the PERMANENT station id the HkoStation setting stores
//! (0 = off: Garmin weather only). For each station: its name in the minute temperature feed,
//! the humidity and wind feeds' station to read with it (itself, or the nearest one that
//! reports that element), and its name in the hourly rhrread report ("" when rhrread has no
//! temperature for it). Background-annotated: the fetch runs in the background service.
(:background)
module HkoStations {

    //! The setting's default: Hong Kong Park.
    const DEFAULT_ID = 6;

    const TEMP = [
        "",   // 0
        "Chek Lap Kok",   // 1
        "Cheung Chau",   // 2
        "Clear Water Bay",   // 3
        "Happy Valley",   // 4
        "HK Observatory",   // 5
        "HK Park",   // 6
        "Kai Tak Runway Park",   // 7
        "Kau Sai Chau",   // 8
        "King's Park",   // 9
        "Kowloon City",   // 10
        "Kwun Tong",   // 11
        "Lau Fau Shan",   // 12
        "Ngong Ping",   // 13
        "Pak Tam Chung",   // 14
        "Peng Chau",   // 15
        "Sai Kung",   // 16
        "Sha Tin",   // 17
        "Sham Shui Po",   // 18
        "Shau Kei Wan",   // 19
        "Shek Kong",   // 20
        "Sheung Shui",   // 21
        "Stanley",   // 22
        "Ta Kwu Ling",   // 23
        "Tai Lung",   // 24
        "Tai Mei Tuk",   // 25
        "Tai Mo Shan",   // 26
        "Tai Po",   // 27
        "Tate's Cairn",   // 28
        "The Peak",   // 29
        "Tseung Kwan O",   // 30
        "Tsing Yi",   // 31
        "Tsuen Wan Ho Koon",   // 32
        "Tsuen Wan Shing Mun Valley",   // 33
        "Tuen Mun",   // 34
        "Waglan Island",   // 35
        "Wetland Park",   // 36
        "Wong Chuk Hang",   // 37
        "Wong Tai Sin",   // 38
        "Yuen Long Park",   // 39
    ] as Array<String>;

    const HUM = [
        "",   // 0
        "Chek Lap Kok",   // 1
        "Cheung Chau",   // 2
        "Clear Water Bay",   // 3
        "HK Park",   // 4
        "HK Observatory",   // 5
        "HK Park",   // 6
        "Kai Tak Runway Park",   // 7
        "Kau Sai Chau",   // 8
        "King's Park",   // 9
        "Kowloon City",   // 10
        "Kai Tak Runway Park",   // 11
        "Lau Fau Shan",   // 12
        "Chek Lap Kok",   // 13
        "Pak Tam Chung",   // 14
        "Peng Chau",   // 15
        "Sai Kung",   // 16
        "Sha Tin",   // 17
        "Tsing Yi",   // 18
        "Shau Kei Wan",   // 19
        "Shek Kong",   // 20
        "Sheung Shui",   // 21
        "Wong Chuk Hang",   // 22
        "Ta Kwu Ling",   // 23
        "Tai Lung",   // 24
        "Tai Po",   // 25
        "Shek Kong",   // 26
        "Tai Po",   // 27
        "Kowloon City",   // 28
        "HK Park",   // 29
        "Tseung Kwan O",   // 30
        "Tsing Yi",   // 31
        "Tsing Yi",   // 32
        "Tsing Yi",   // 33
        "Tuen Mun",   // 34
        "Waglan Island",   // 35
        "Wetland Park",   // 36
        "Wong Chuk Hang",   // 37
        "Kowloon City",   // 38
        "Wetland Park",   // 39
    ] as Array<String>;

    const WIND = [
        "",   // 0
        "Chek Lap Kok",   // 1
        "Cheung Chau",   // 2
        "Tseung Kwan O",   // 3
        "Wong Chuk Hang",   // 4
        "King's Park",   // 5
        "Central Pier",   // 6
        "Kai Tak",   // 7
        "Sai Kung",   // 8
        "King's Park",   // 9
        "King's Park",   // 10
        "Kai Tak",   // 11
        "Lau Fau Shan",   // 12
        "Ngong Ping",   // 13
        "Sai Kung",   // 14
        "Peng Chau",   // 15
        "Sai Kung",   // 16
        "Sha Tin",   // 17
        "King's Park",   // 18
        "Kai Tak",   // 19
        "Shek Kong",   // 20
        "Ta Kwu Ling",   // 21
        "Stanley",   // 22
        "Ta Kwu Ling",   // 23
        "Ta Kwu Ling",   // 24
        "Tai Mei Tuk",   // 25
        "Shek Kong",   // 26
        "Tai Po Kau",   // 27
        "Tate's Cairn",   // 28
        "Wong Chuk Hang",   // 29
        "Tseung Kwan O",   // 30
        "Tsing Yi",   // 31
        "Tsing Yi",   // 32
        "Tsing Yi",   // 33
        "Tuen Mun",   // 34
        "Waglan Island",   // 35
        "Wetland Park",   // 36
        "Wong Chuk Hang",   // 37
        "Kai Tak",   // 38
        "Wetland Park",   // 39
    ] as Array<String>;

    const RHR = [
        "",   // 0
        "Chek Lap Kok",   // 1
        "Cheung Chau",   // 2
        "",   // 3
        "Happy Valley",   // 4
        "Hong Kong Observatory",   // 5
        "Hong Kong Park",   // 6
        "Kai Tak Runway Park",   // 7
        "",   // 8
        "King's Park",   // 9
        "Kowloon City",   // 10
        "Kwun Tong",   // 11
        "Lau Fau Shan",   // 12
        "",   // 13
        "",   // 14
        "",   // 15
        "Sai Kung",   // 16
        "Sha Tin",   // 17
        "Sham Shui Po",   // 18
        "Shau Kei Wan",   // 19
        "Shek Kong",   // 20
        "",   // 21
        "Stanley",   // 22
        "Ta Kwu Ling",   // 23
        "",   // 24
        "Tai Mei Tuk",   // 25
        "",   // 26
        "Tai Po",   // 27
        "",   // 28
        "",   // 29
        "Tseung Kwan O",   // 30
        "Tsing Yi",   // 31
        "Tsuen Wan Ho Koon",   // 32
        "Tsuen Wan Shing Mun Valley",   // 33
        "Tuen Mun",   // 34
        "",   // 35
        "",   // 36
        "Wong Chuk Hang",   // 37
        "Wong Tai Sin",   // 38
        "Yuen Long Park",   // 39
    ] as Array<String>;

    //! The selected station id, clamped (a hand-edited or stale value falls back to the default;
    //! 0 stays 0 = off).
    function selected() as Number {
        var v = Application.Properties.getValue("HkoStation");
        if (v instanceof Lang.Number && (v as Number) >= 0 && (v as Number) < TEMP.size()) {
            return v as Number;
        }
        return DEFAULT_ID;
    }
}
