"""The full-face VFD mesh tile shared by every Claude watch face (garmin/shared/resources-mesh/).

A MESH_TILE-square PNG of black grid lines at MESH_DIM alpha - every MESH_PITCH-th screen row and
column - tiled over the whole face as the LAST draw step, so the time, text, icons, rings and
arcs share ONE grid in ONE phase. (Baking a mesh into each font glyph or bitmap would put each
element's grid in a different phase.) Tiles are drawn from the screen origin in MESH_TILE steps
and MESH_TILE % MESH_PITCH == 0, so tile-local (x % 3 == 2) is screen (x % 3 == 2) everywhere:
one continuous grid. 4 x 4 tiles of 114 px cover a 454 px screen.

packingFormat="png" on the <bitmap> is REQUIRED: the default packing converts to the panel's
16-bit format with a 1-bit transparency key, which turns the 30 % alpha lines solid black.

Both faces' glow generators call write_mesh_tile() (Claude Grid's build_glow_digits.py and
Claude Terminal's build_glow_time.py), so regenerating either face refreshes the shared tile,
and both always write byte-identical output. Claude Terminal also imports MESH_TILE for its own
scanline tile, which must line up with the screen the same way.

Run standalone from anywhere:  python garmin/shared/tools/mesh_tile.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
SHARED = HERE.parent                                   # garmin/shared/
MESH_DIR = SHARED / "resources-mesh" / "drawables"

MESH_PITCH = 3           # every third screen row / column is a grid line
MESH_DIM = 0.30          # grid-line alpha (0..1); black lines, so this is how much they darken
MESH_TILE = 114          # tile edge in px - must be a multiple of MESH_PITCH (checked below)


def write_mesh_tile() -> Path:
    """Write mesh_tile.png and its drawables.xml into garmin/shared/resources-mesh/drawables/.

    Returns the PNG path. Deterministic: the same constants always produce the same bytes.
    """
    if MESH_TILE % MESH_PITCH != 0:
        # A tile edge that is not a whole number of pitches would put a seam (a doubled or
        # missing line) at every tile boundary.
        raise ValueError("MESH_TILE (%d) must be a multiple of MESH_PITCH (%d)" % (MESH_TILE, MESH_PITCH))
    yy, xx = np.mgrid[0:MESH_TILE, 0:MESH_TILE]
    line = ((yy % MESH_PITCH) == MESH_PITCH - 1) | ((xx % MESH_PITCH) == MESH_PITCH - 1)
    rgba = np.zeros((MESH_TILE, MESH_TILE, 4), dtype=np.uint8)   # RGB stays 0 = black lines
    rgba[..., 3] = np.where(line, int(round(MESH_DIM * 255)), 0)
    MESH_DIR.mkdir(parents=True, exist_ok=True)
    out = MESH_DIR / "mesh_tile.png"
    Image.fromarray(rgba, "RGBA").save(out, optimize=True)
    (MESH_DIR / "drawables.xml").write_text(
        "<drawables>\n"
        "    <!-- Generated by garmin/shared/tools/mesh_tile.py - do not edit. Full-face VFD mesh\n"
        "         tile shared by every face, tiled over the whole face last. packingFormat=\"png\"\n"
        "         keeps the partial alpha (the default packing would turn it into a 1-bit key =\n"
        "         solid black lines). -->\n"
        '    <bitmap id="MeshTile" filename="mesh_tile.png" packingFormat="png" />\n'
        "</drawables>\n", encoding="utf-8", newline="\n")
    return out


def main() -> int:
    out = write_mesh_tile()
    print("mesh -> %s (%dpx tile, pitch %d, dim %.2f)" % (out, MESH_TILE, MESH_PITCH, MESH_DIM))
    return 0


if __name__ == "__main__":
    sys.exit(main())
